"""facilities table

Revision ID: 678050f3e124
Revises: 
Create Date: 2019-02-22 10:07:53.684542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678050f3e124'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('current_capacity', sa.Integer(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_facility_address'), 'facility', ['address'], unique=True)
    op.create_index(op.f('ix_facility_email'), 'facility', ['email'], unique=True)
    op.create_index(op.f('ix_facility_username'), 'facility', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_username'), table_name='facility')
    op.drop_index(op.f('ix_facility_email'), table_name='facility')
    op.drop_index(op.f('ix_facility_address'), table_name='facility')
    op.drop_table('facility')
    # ### end Alembic commands ###
